# Generated by Django 5.0.6 on 2024-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accused",
            name="accused_location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="accuser",
            name="accuser_location",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
